# Generated by Django 3.2.16 on 2023-01-13 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(default='anonymous', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('describe', models.TextField(default='DataFlair Django tutorials')),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=7)),
                ('zone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdminUserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_endpoint', models.TextField(blank=True, max_length=200, null=True)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.superadminuser')),
            ],
        ),
    ]
