# Generated by Django 3.2.16 on 2023-10-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20230113_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('orgn', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('emergency_mobile', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('marriage_date', models.DateField()),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
            ],
        ),
    ]
