# Generated by Django 3.2.16 on 2023-10-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employee Master',
        ),
    ]
